name: Hello World!
run-name: Hello World!
env:
  COMMIT: ${{ join(toJSON(github.event.commits.*.message)) }}
on:
  push:
    branches:
      - main
jobs:
  Hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
      - name: Now it is
        run: date
      - name: Directory content
        run: ls -l
      - name: Commit messages
        run: echo "$COMMIT"